version: "3"
services:
  server:
    build: ./server
    container_name: pre-kakeibo-server
    ports:
      - "8082:8082"
    restart: always

  db:
    image: mysql
    ports:
      - "3306:3306"
    container_name: pre-kakeibo-db
    environment:
      MYSQL_DATABASE: pre-kakeibo
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - pre-kakeibo-data:/var/lib/mysql

  migration:
    build: ./database
    container_name: pre-kakeibo-migration
    tty: true

volumes:
  pre-kakeibo-data:

